### ISSUE TITLE
Add "How to use" to readme

### ISSUE THREAD

**Issue by Wikunia** [fdecampredon/brackets-flow#2]
Hi,

I would like to use flow inside brackets and would like to help to improve this extension.
Unfortunately I have no idea how to start your extension. Can you update your readme, pls?

**Comment by fdecampredon** [comment]
@Wikunia is the readme ok for you now ?

**Comment by Wikunia** [comment]
@fdecampredon I don't know how to see the flow logs inside brackets :) I started flow but how to run it inside brackets? Is there a menu to see the logs or sth. like that?

**Comment by fdecampredon** [comment]
@Wikunia you don't have flow errors inside error panel ? don't forget to add `/* @flow */` on top of your file

**Comment by Wikunia** [comment]
@fdecampredon ah okay sry my mistake, thought it's harder :D 
But I have an error: `Flow terminated with error: [object Object]`

**Comment by Wikunia** [comment]
/language/CodeInspection.js:227 => [CodeInspection] Provider Flow (async) failed: [object Object]

**Comment by fdecampredon** [comment]
@Wikunia sounds like a  bug :D I need more info to fix it could you please try to debug a bit ?
I think a good starting point is to debug the node domain to see if the flow command fail : https://github.com/fdecampredon/brackets-flow/blob/master/node/flowDomain.js#L13 and if the JSON returned by flow is valid (sometimes it's not the case)

**Comment by Wikunia** [comment]
@fdecampredon was my mistake again :D I installed flow with root and that creates the `/tmp/flow/` dir where my user doesn't have the right to write so it couldn't work. Thanks for this extension :)

**Comment by fdecampredon** [comment]
no problem @Wikunia ;) feel free to report bugs
